version: '3.8'

services:
  userdb:
    image: mysql:latest
    container_name: userdb
    restart: unless-stopped
    environment: # add default values
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdb # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3307:3306"
  api:
    build: . # Use the dockerfile from the current directory to build the containerf
    container_name: go-api # add a name for the container
    ports:
      - "8080:8080"
    environment:
      - WAIT_HOSTS=userdb:3307
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    volumes:
     - .:/usr/src/app
    command: air src/main.go -b 0.0.0.0
    depends_on:
      - "userdb"

volumes: # add volume to persist data.
  my-db: