version: '3.8'

services:
  api:
    build: . # Use the dockerfile from the current directory to build the containerf
    container_name: go-api # add a name for the container
    ports:
      - 8080:8080
    volumes:
     - .:/usr/src/app
    command: air src/main.go -b 0.0.0.0
  
  db:
    image: mysql:latest
    container_name: user-db
    restart: unless-stopped
    environment: # add default values
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdb # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - 3306:3306

volumes: # add volume to persist data.
  my-db: